version: "3"

networks:
  app:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app

  milk-games-web:
    build:
      context: .
      dockerfile: web.dockerfile
    container_name: milk-games-web
    ports:
      - "${WEB_PORT_FROM}:${WEB_PORT_TO}"
    environment:
      REACT_APP_API_URL: http://${API_HOST}
      REACT_APP_AUTH_ENABLED: "true"
    volumes:
      - "./build:/var/www/react"
    networks:
      - app

  milk-games-api:
    build:
      context: .
      dockerfile: api.dockerfile
    container_name: milk-games-api
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - "${API_PORT_FROM}:${API_PORT_TO}"
    env_file:
      - .env
    environment:
      - WEB_URL=http://${WEB_HOST}
      - API_URL=http://${API_HOST}
    networks:
      - app

  mysql:
    image: mysql:8.0.32
    container_name: milk-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT_FROM}:${MYSQL_PORT_TO}"
    env_file:
      - .env
    environment:
      MYSQL_USER: ""
      SERVICE_TAGS: dev
      SERVICE_NAME: milk-mysql
    networks:
      - app
