name: Maven Build API
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      #Set up Maven cache
      #This action allows caching dependencies and build outputs to improve workflow execution time.
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # Build the JAR with Maven
      - name: Clean install
        run: mvn clean install -DskipTests -ntp
      # Upload JAR artifact
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          #Set artifact name
          name: artifact
          #From this path
          path: milk-games-api/target/milk-games-api-0.0.1-SNAPSHOT.jar